### ISSUE TITLE
rpmlint reports: W: manual-page-warning

### ISSUE THREAD

**Issue by martinkg** [j-jorge/bear#7]
rpmlint reports this warnings:

`bear-engine.x86_64: W: manual-page-warning /usr/share/man/man6/running-bear.6.gz 5: warning: macro `RS' not defined
bear-engine.x86_64: W: manual-page-warning /usr/share/man/man6/running-bear.6.gz 12: warning: macro `RE' not defined
bear-factory.x86_64: W: manual-page-warning /usr/share/man/man1/bf-model-editor.1.gz 5: warning: macro `RS' not defined
bear-factory.x86_64: W: manual-page-warning /usr/share/man/man1/bf-model-editor.1.gz 12: warning: macro `RE' not defined
bear-factory.x86_64: W: manual-page-warning /usr/share/man/man1/bf-level-editor.1.gz 5: warning: macro `RS' not defined
bear-factory.x86_64: W: manual-page-warning /usr/share/man/man1/bf-level-editor.1.gz 12: warning: macro `RE' not defined
bear-factory.x86_64: W: manual-page-warning /usr/share/man/man1/bf-animation-editor.1.gz 5: warning: macro `RS' not defined
bear-factory.x86_64: W: manual-page-warning /usr/share/man/man1/bf-animation-editor.1.gz 12: warning: macro `RE' not defined`

**Comment by j-jorge** [comment]
I am not sure if I can do something about it. The man pages are written in DocBook and converted using `docbook-to-man`. Unless there is a change to do in the DocBook file then the problem is in `docbook-to-man`.

**Comment by martinkg** [comment]
Problem solved by editing the *.sgml files.
# convert docbook2man filename taken from .sgml file to lowercase
sed -i 's|<refentrytitle>\(.*\)</refentrytitle>|<refentrytitle>\L\1</refentrytitle>|' bear-*/desktop/man/*.sgml
